// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	Post      string     `json:"post"`
	Author    string     `json:"author"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	ReplyTo   *string    `json:"replyTo,omitempty"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type CommentIntput struct {
	Post    string  `json:"post"`
	ReplyTo *string `json:"replyTo,omitempty"`
	Author  string  `json:"author"`
	Content string  `json:"content"`
}

type Mutation struct {
}

type Post struct {
	ID        string `json:"id"`
	Author    string `json:"author"`
	Header    string `json:"header"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type PostInput struct {
	Author          string `json:"author"`
	Header          string `json:"header"`
	Content         string `json:"content"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type PostOutput struct {
	ID              string     `json:"id"`
	Author          string     `json:"author"`
	Header          string     `json:"header"`
	Content         string     `json:"content"`
	CommentsAllowed bool       `json:"commentsAllowed"`
	CreatedAt       string     `json:"createdAt"`
	Comments        []*Comment `json:"comments,omitempty"`
}

type Query struct {
}
